config/routes.rb
Rails.application.routes.draw do
	root to: 'home#index'

  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  include ActionView::Helpers::DateHelper

  validate :ends_at_is_after_starts_at

  def ends_at_is_after_starts_at
    if starts_at > ends_at
      errors.add(:ends_at, "must be after starts at")
    end
  end

  scope :active, -> { where("ends_at > ?", Time.now) }

	def going_on_now?
		starts_at < Time.now && ends_at > Time.now
	end

  def happening_class
    if going_on_now?
      "happening"
    else
      "not_happening"
    end
  end

  def start_or_end_string
    if going_on_now?
      "End"
    else
      "Start"
    end
  end

	def time_until
		if going_on_now?
      time_ago_in_words(ends_at)
    else
      time_ago_in_words(starts_at)
    end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:starts_at, :ends_at)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@events = Event.active.order(:starts_at).to_a
    @active_event = @events.shift
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :starts_at %>
    <%= form.datetime_select :starts_at, { ampm: true, minute_step: 60 }, id: :event_starts_at %>
  </div>

  <div class="field">
    <%= form.label :ends_at %>
    <%= form.datetime_select :ends_at, { ampm: true, minute_step: 60 }, id: :event_ends_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Starts at</th>
      <th>Ends at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.starts_at %></td>
        <td><%= event.ends_at %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Starts at:</strong>
  <%= @event.starts_at %>
</p>

<p>
  <strong>Ends at:</strong>
  <%= @event.ends_at %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/home/index.html.erb
<div class="container home">
  <%= image_tag "salmon-run-logo.png", class: "logo" %>

	<% if @active_event %>
	<section class="active-event <%= @active_event.happening_class %>">

    <% if @active_event.going_on_now? %>
      <%= image_tag "Salmon-Run-Orange-Shape.png", class: "orange-shape" %>
      <h2>It's Salmon Run Time!</h2>
    <% end %>

	  <p class="time-until">Time Until <%= @active_event.start_or_end_string %>: <%= @active_event.time_until %></p>

    <p class="time-until-date">
    <% if !@active_event.going_on_now? %>
      ( Starts <%= @active_event.starts_at.to_s(:full_date_string) %> )
    <% else %>
      ( Ends <%= @active_event.ends_at.to_s(:full_date_string) %> )
    <% end %>
    </p>

	</section>
	<% end %>
  <section class="future-events">
  	<ul>
  	<% @events.each do |event| %>
  		<li><span><%= event.starts_at.to_s(:full_date_string) %> - <%= event.ends_at.to_s(:full_date_string) %></span> <span class="event-time-until"><%= event.time_until %></span></li>
  	<% end %>
    </ul>
    <%= image_tag "salmon-run-char.png", class: "char" %>
    <%= image_tag "salmon-run-char-2.png", class: "char-2" %>
  </section>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Splatime</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>